version: "2"
services:
    memcached:
        image: memcached:latest
        container_name: dockerMemcached
        restart: always
        ports:
            - "11211:11211"
    mariadb:
        image: mariadb:latest
        container_name: dockerMariadb
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./mariadb/data:/var/lib/mysql
        env_file: ./mariadb/env
    php-fpm:
        build: ./php
        container_name: dockerPhp
        restart: always
        volumes:
            - ./www:/var/www/html
        links:
            - mariadb
            - memcached
        depends_on:
            - mariadb
            - memcached
    nginx:
        image: nginx:latest
        container_name: dockerHttpd
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php-fpm
        links:
            - php-fpm
        depends_on:
            - php-fpm
    composer:
        build: ./composer
        container_name: dockerComposer
        command: install
        volumes:
            - ./www:/app
            - ~/.ssh:/root/.ssh
        depends_on:
            - php-fpm
