FROM composer/composer:latest
RUN /usr/local/bin/composer self-update
RUN /usr/local/bin/composer global require "fxp/composer-asset-plugin"
RUN /usr/local/bin/composer global show fxp/composer-asset-plugin
